- name: Certificate Syncing
  hosts: zookeeper:kafka_broker:schema_registry:kafka_connect:ksql:control_center:kafka_rest
  gather_facts: yes
  tags:
    - always
  tasks:
  - import_role:
      name: confluent.ssl_sync
    when: security_mode in ["kerberos_ssl_customcerts", "ssl_customcerts", "ssl", "sasl_ssl", "kerberos_ssl"]

- name: Kafta Connect Provisioning
  hosts: kafka_connect
  gather_facts: no
  tags:
    - kafka_connect
  tasks:
  - import_role:
      name: confluent.kafka_connect

- name: KSQL Provisioning
  hosts: ksql
  gather_facts: no
  tags:
    - ksql
  tasks:
  - import_role:
      name: confluent.ksql

- name: Control Center Provisioning
  hosts: control_center
  gather_facts: no
  tags:
    - control_center
  tasks:
  - import_role:
      name: confluent.control_center

- name: Kafka Rest Provisioning
  hosts: kafka_rest
  gather_facts: no
  tags:
    - kafka_rest
  tasks:
  - import_role:
      name: confluent.kafka_rest
